server:
  port: 8083

spring:
  application:
    name: ebuy-account-service

eureka:
  client:
    service-url:
      defaultZone: https://ebuy-registry-service.herokuapp.com/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
